// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,optimize_code_size
// @generated from protobuf file "browse.response.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://youtubei.googleapis.com/youtubei/v1/browse
 *
 * @generated from protobuf message Browse
 */
export interface Browse {
    /**
     * Context responseContext = 1;
     *
     * @generated from protobuf field: Renderers contents = 9;
     */
    contents?: Renderers;
    /**
     * @generated from protobuf field: Renderers continuationContents = 10;
     */
    continuationContents?: Renderers;
}
/**
 *
 * message Context {
 * repeated ServiceTrackingParams serviceTrackingParams = 6;
 * int32 maxAgeSeconds = 7;
 * };
 *
 * @generated from protobuf message Renderers
 */
export interface Renderers {
    /**
     * @generated from protobuf field: SectionListRenderer sectionListRenderer = 49399797;
     */
    sectionListRenderer?: SectionListRenderer;
    /**
     * @generated from protobuf field: n4F50195462 n4F50195462 = 50195462;
     */
    n4F50195462?: n4F50195462;
    /**
     * n6F51431404 n6F51431404 = 51431404;
     * n4F51845067 n4F51845067 = 51845067;
     *
     * @generated from protobuf field: SingleColumnBrowseResultsRenderer singleColumnBrowseResultsRenderer = 58173949;
     */
    singleColumnBrowseResultsRenderer?: SingleColumnBrowseResultsRenderer;
    /**
     * @generated from protobuf field: MusicSideAlignedItemRenderer musicSideAlignedItemRenderer = 90823135;
     */
    musicSideAlignedItemRenderer?: MusicSideAlignedItemRenderer;
    /**
     * @generated from protobuf field: GridRenderer gridRenderer = 91303872;
     */
    gridRenderer?: GridRenderer;
    /**
     * @generated from protobuf field: n6F153515154 n6F153515154 = 153515154;
     */
    n6F153515154?: n6F153515154;
    /**
     * n11F172035250 n11F172035250 = 172035250;
     * n7F172660663 n7F172660663 = 172660663;
     *
     * @generated from protobuf field: MusicDescriptionShelfRenderer musicDescriptionShelfRenderer = 221496734;
     */
    musicDescriptionShelfRenderer?: MusicDescriptionShelfRenderer;
}
/**
 *
 * message ServiceTrackingParams {
 * //serviceType service = 1;
 * map<string, string> params = 2;
 * };
 *
 * @generated from protobuf message SingleColumnBrowseResultsRenderer
 */
export interface SingleColumnBrowseResultsRenderer {
    /**
     * @generated from protobuf field: repeated Tabs tabs = 1;
     */
    tabs: Tabs[];
}
/**
 * @generated from protobuf message MusicSideAlignedItemRenderer
 */
export interface MusicSideAlignedItemRenderer {
    /**
     * @generated from protobuf field: repeated Renderers startItems = 1;
     */
    startItems: Renderers[];
}
/**
 * @generated from protobuf message GridRenderer
 */
export interface GridRenderer {
    /**
     * @generated from protobuf field: repeated Renderers items = 1;
     */
    items: Renderers[];
}
/**
 * @generated from protobuf message Tabs
 */
export interface Tabs {
    /**
     * @generated from protobuf field: TabRenderer tabRenderer = 58174010;
     */
    tabRenderer?: TabRenderer;
}
/**
 * @generated from protobuf message TabRenderer
 */
export interface TabRenderer {
    /**
     * @generated from protobuf field: optional string title = 2;
     */
    title?: string;
    /**
     * @generated from protobuf field: bool selected = 3;
     */
    selected: boolean;
    /**
     * @generated from protobuf field: Renderers content = 4;
     */
    content?: Renderers;
    /**
     * @generated from protobuf field: optional string tabIdentifier = 11;
     */
    tabIdentifier?: string;
}
/**
 * @generated from protobuf message SectionListRenderer
 */
export interface SectionListRenderer {
    /**
     * @generated from protobuf field: repeated Renderers contents = 1;
     */
    contents: Renderers[];
    /**
     * @generated from protobuf field: Renderers header = 6;
     */
    header?: Renderers;
}
/**
 * sectionListRenderer ?? musicDescriptionShelfRenderer
 *
 * @generated from protobuf message n4F50195462
 */
export interface n4F50195462 {
    /**
     * @generated from protobuf field: repeated Renderers n5F1 = 1;
     */
    n5F1: Renderers[];
}
/**
 *
 * message n4F51845067 {
 * Renderers n5F5 = 5;
 * };
 *
 * message n6F51431404 {
 * repeated Renderers n5F1 = 1;
 * };
 *
 * @generated from protobuf message MusicDescriptionShelfRenderer
 */
export interface MusicDescriptionShelfRenderer {
    /**
     * @generated from protobuf field: Description description = 3;
     */
    description?: Description;
    /**
     * @generated from protobuf field: Footer footer = 10;
     */
    footer?: Footer;
}
/**
 * @generated from protobuf message Description
 */
export interface Description {
    /**
     * n6F1 n6F1 = 1; // Runs
     *
     * @generated from protobuf field: repeated Runs runs = 1;
     */
    runs: Runs[];
}
/**
 * description?
 *
 * @generated from protobuf message n6F153515154
 */
export interface n6F153515154 {
    /**
     * @generated from protobuf field: n7F172660663 n7F172660663 = 172660663;
     */
    n7F172660663?: n7F172660663;
}
/**
 * @generated from protobuf message n7F172660663
 */
export interface n7F172660663 {
    /**
     * @generated from protobuf field: n8F1 n8F1 = 1;
     */
    n8F1?: n8F1;
}
/**
 * @generated from protobuf message Footer
 */
export interface Footer {
    /**
     * Origin origin = 1;
     *
     * @generated from protobuf field: repeated Runs runs = 1;
     */
    runs: Runs[];
}
/**
 * content?
 *
 * @generated from protobuf message n8F1
 */
export interface n8F1 {
    /**
     * @generated from protobuf field: n9F168777401 n9F168777401 = 168777401;
     */
    n9F168777401?: n9F168777401;
}
/**
 *
 * message n8F2 { // header?
 * n9F183314536 n9F183314536 = 183314536;
 * };
 *
 * message n8F3 {
 * n8F1 n8F1 = 1;
 * n8F2 n8F2 = 2;
 * };
 *
 * message Origin { // runs
 * string originText = 1; //text
 * };
 *
 * @generated from protobuf message n9F168777401
 */
export interface n9F168777401 {
    /**
     * n10F3 n10F3 = 3;
     *
     * @generated from protobuf field: n10F5 n10F5 = 5;
     */
    n10F5?: n10F5;
}
/**
 * @generated from protobuf message n10F5
 */
export interface n10F5 {
    /**
     * @generated from protobuf field: n11F465160965 n11F465160965 = 465160965;
     */
    n11F465160965?: n11F465160965;
}
/**
 * @generated from protobuf message n11F465160965
 */
export interface n11F465160965 {
    /**
     * @generated from protobuf field: n12F4 n12F4 = 4;
     */
    n12F4?: n12F4;
}
/**
 * Name
 *
 * @generated from protobuf message n12F4
 */
export interface n12F4 {
    /**
     * @generated from protobuf field: repeated n13F1 n13F1 = 1;
     */
    n13F1: n13F1[];
    /**
     * @generated from protobuf field: string originText = 2;
     */
    originText: string;
}
/**
 * Runs
 *
 * @generated from protobuf message n13F1
 */
export interface n13F1 {
    /**
     * @generated from protobuf field: string f1 = 1;
     */
    f1: string;
}
/**
 *
 * message n11F172035250 {
 * string type = 1;
 * };
 *
 * Runs
 *
 * @generated from protobuf message Runs
 */
export interface Runs {
    /**
     * @generated from protobuf field: string text = 1;
     */
    text: string;
}
declare class Browse$Type extends MessageType<Browse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Browse
 */
export declare const Browse: Browse$Type;
declare class Renderers$Type extends MessageType<Renderers> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Renderers
 */
export declare const Renderers: Renderers$Type;
declare class SingleColumnBrowseResultsRenderer$Type extends MessageType<SingleColumnBrowseResultsRenderer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message SingleColumnBrowseResultsRenderer
 */
export declare const SingleColumnBrowseResultsRenderer: SingleColumnBrowseResultsRenderer$Type;
declare class MusicSideAlignedItemRenderer$Type extends MessageType<MusicSideAlignedItemRenderer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message MusicSideAlignedItemRenderer
 */
export declare const MusicSideAlignedItemRenderer: MusicSideAlignedItemRenderer$Type;
declare class GridRenderer$Type extends MessageType<GridRenderer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message GridRenderer
 */
export declare const GridRenderer: GridRenderer$Type;
declare class Tabs$Type extends MessageType<Tabs> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Tabs
 */
export declare const Tabs: Tabs$Type;
declare class TabRenderer$Type extends MessageType<TabRenderer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message TabRenderer
 */
export declare const TabRenderer: TabRenderer$Type;
declare class SectionListRenderer$Type extends MessageType<SectionListRenderer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message SectionListRenderer
 */
export declare const SectionListRenderer: SectionListRenderer$Type;
declare class n4F50195462$Type extends MessageType<n4F50195462> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n4F50195462
 */
export declare const n4F50195462: n4F50195462$Type;
declare class MusicDescriptionShelfRenderer$Type extends MessageType<MusicDescriptionShelfRenderer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message MusicDescriptionShelfRenderer
 */
export declare const MusicDescriptionShelfRenderer: MusicDescriptionShelfRenderer$Type;
declare class Description$Type extends MessageType<Description> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Description
 */
export declare const Description: Description$Type;
declare class n6F153515154$Type extends MessageType<n6F153515154> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n6F153515154
 */
export declare const n6F153515154: n6F153515154$Type;
declare class n7F172660663$Type extends MessageType<n7F172660663> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n7F172660663
 */
export declare const n7F172660663: n7F172660663$Type;
declare class Footer$Type extends MessageType<Footer> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Footer
 */
export declare const Footer: Footer$Type;
declare class n8F1$Type extends MessageType<n8F1> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n8F1
 */
export declare const n8F1: n8F1$Type;
declare class n9F168777401$Type extends MessageType<n9F168777401> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n9F168777401
 */
export declare const n9F168777401: n9F168777401$Type;
declare class n10F5$Type extends MessageType<n10F5> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n10F5
 */
export declare const n10F5: n10F5$Type;
declare class n11F465160965$Type extends MessageType<n11F465160965> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n11F465160965
 */
export declare const n11F465160965: n11F465160965$Type;
declare class n12F4$Type extends MessageType<n12F4> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n12F4
 */
export declare const n12F4: n12F4$Type;
declare class n13F1$Type extends MessageType<n13F1> {
    constructor();
}
/**
 * @generated MessageType for protobuf message n13F1
 */
export declare const n13F1: n13F1$Type;
declare class Runs$Type extends MessageType<Runs> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Runs
 */
export declare const Runs: Runs$Type;
export {};
