// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "get_watch.response.proto" (package "youtube.api.innertube", syntax proto2)
// tslint:disable
//
// This file is generated by protobuf-toolkit. DO NOT EDIT! 
//
import { MessageType } from "@protobuf-ts/runtime";
import { PlayerResponse } from "./player.response";
/**
 * @generated from protobuf message youtube.api.innertube.GetWatchResponse
 */
export interface GetWatchResponse {
    /**
     * optional ResponseContext responseContext = 1;
     *
     * @generated from protobuf field: optional PlayerResponse playerResponse = 2;
     */
    playerResponse?: PlayerResponse;
    /**
     * @generated from protobuf field: optional youtube.api.innertube.WatchNextResponse watchNextResponse = 3;
     */
    watchNextResponse?: WatchNextResponse;
    /**
     * @generated from protobuf field: optional string getPlayerErrorMsg = 4;
     */
    getPlayerErrorMsg?: string;
    /**
     * @generated from protobuf field: optional string getWatchNextErrorMsg = 5;
     */
    getWatchNextErrorMsg?: string;
}
/**
 * @generated from protobuf message youtube.api.innertube.WatchNextResponse
 */
export interface WatchNextResponse {
}
declare class GetWatchResponse$Type extends MessageType<GetWatchResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message youtube.api.innertube.GetWatchResponse
 */
export declare const GetWatchResponse: GetWatchResponse$Type;
declare class WatchNextResponse$Type extends MessageType<WatchNextResponse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message youtube.api.innertube.WatchNextResponse
 */
export declare const WatchNextResponse: WatchNextResponse$Type;
export {};
