// @generated by protobuf-ts 2.9.1 with parameter long_type_string,output_javascript,optimize_code_size
// @generated from protobuf file "browse.request.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * https://youtubei.googleapis.com/youtubei/v1/browse
 *
 * @generated from protobuf message Browse
 */
export interface Browse {
    /**
     * @generated from protobuf field: Context context = 1;
     */
    context?: Context;
    /**
     * @generated from protobuf field: string browseId = 2;
     */
    browseId: string;
}
/**
 * @generated from protobuf message Context
 */
export interface Context {
    /**
     * @generated from protobuf field: Client client = 1;
     */
    client?: Client;
    /**
     * @generated from protobuf field: AdSignalsInfo adSignalsInfo = 9;
     */
    adSignalsInfo?: AdSignalsInfo;
}
/**
 * @generated from protobuf message Client
 */
export interface Client {
    /**
     * @generated from protobuf field: optional string hl = 1;
     */
    hl?: string;
    /**
     * @generated from protobuf field: optional string gl = 2;
     */
    gl?: string;
    /**
     * @generated from protobuf field: string deviceMake = 12;
     */
    deviceMake: string;
    /**
     * @generated from protobuf field: string deviceModel = 13;
     */
    deviceModel: string;
    /**
     * string visitorData = 14;
     * string userAgent = 15;
     *
     * @generated from protobuf field: int32 clientName = 16;
     */
    clientName: number;
    /**
     * @generated from protobuf field: string clientVersion = 17;
     */
    clientVersion: string;
    /**
     * string browserVersion = 17;
     *
     * @generated from protobuf field: string osName = 18;
     */
    osName: string;
    /**
     * @generated from protobuf field: string osVersion = 19;
     */
    osVersion: string;
    /**
     * int32 screenWidthPoints = 37; //??
     * int32 screenHeightPoints = 38; //??
     * optional int32 screenPixelDensity = 41 //??
     * int32 screenWidthPoints = 55; //??
     * int32 screenHeightPoints = 56; //??
     * configInfo configInfo = 62;
     * optional int32 screenDensityFloat = 65; //??
     * optional int32 utcOffsetMinutes = 63;
     * userInterfaceThemType userInterfaceTheme = 78; //??
     *
     * @generated from protobuf field: string timeZone = 80;
     */
    timeZone: string;
}
/**
 * @generated from protobuf message AdSignalsInfo
 */
export interface AdSignalsInfo {
    /**
     * @generated from protobuf field: map<string, string> params = 1;
     */
    params: {
        [key: string]: string;
    };
}
declare class Browse$Type extends MessageType<Browse> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Browse
 */
export declare const Browse: Browse$Type;
declare class Context$Type extends MessageType<Context> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Context
 */
export declare const Context: Context$Type;
declare class Client$Type extends MessageType<Client> {
    constructor();
}
/**
 * @generated MessageType for protobuf message Client
 */
export declare const Client: Client$Type;
declare class AdSignalsInfo$Type extends MessageType<AdSignalsInfo> {
    constructor();
}
/**
 * @generated MessageType for protobuf message AdSignalsInfo
 */
export declare const AdSignalsInfo: AdSignalsInfo$Type;
export {};
